// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yecifjjqyotvxnffdcum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllY2lmampxeW90dnhuZmZkY3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDM0MzYsImV4cCI6MjA3MDExOTQzNn0.j0FQYEHAWxJRGAKFKlq7HiQpO1Larb_mxZuVvQqKsG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});