// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpsuhnlkhdhytsokcpmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwc3VobmxraGRoeXRzb2tjcG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzg5NDAsImV4cCI6MjA3MDc1NDk0MH0.lkI-Te9FD7iMe0-HOpAYtqZB6OeUbgL7gE25Jto6SDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});